### ISSUE TITLE
Body parameter

### ISSUE THREAD

**Issue by bgaluszka** [apigee-127/swagger-test-templates#118]
Currently this code https://github.com/apigee-127/swagger-test-templates/blob/master/templates/request/post/post.handlebars#L24-L28

```js
        json: {
          {{#each bodyParameters}}
          {{this.name}}: 'DATA GOES HERE'{{#unless @last}},{{/unless}}
          {{/each}}
        }
```

based on this description

```yaml
      parameters:
        - name: User
          description: User
          in: body
          required: true
          schema:
            type: object
            required:
              - email
            properties:
              email:
                description: Email
                type: string 
                format: email
                default: example@example.com
```

generates body that looks like this

```json
{
    User: {
        email: example@example.com
    }
}
```

but I think it should look like this

```json
{
    email: example@example.com
}
```

this is because by http://swagger.io/specification/#parameterObject body is `The payload that's appended to the HTTP request. Since there can only be one payload, there can only be one body parameter. The name of the body parameter has no effect on the parameter itself and is used for documentation purposes only.`.

**Comment by Remco75** [comment]
Yeah, I agree it looks a bit funny. ATM we are building the ability to include request-data during test generation, so you don't have to see the 'DATA GOES HERE' anymore ;-)

**Comment by bgaluszka** [comment]
Point was that `bodyParameters` shouldn't be an array, looped through etc. :)

**Comment by Remco75** [comment]
check, I think we should fix that. @noahdietz do you have any thought about this? I think we should do #117 first before doing anymore work on the templates, right now it's very frustrating to work on them

**Comment by noahdietz** [comment]
@Remco75 agreed, #117 should be merged first before addressing this.

**Comment by baynezy** [comment]
@bgaluszka  - I believe that this has been resolved in #140 . Can you confirm?

**Comment by bgaluszka** [comment]
@baynezy unfortunately I don't have that code/spec anymore since we changed our toolkit and moved to swagger 3.0 :/ I've looked on that part of code and it still there https://github.com/apigee-127/swagger-test-templates/blob/master/templates/request/post/post.handlebars#L29-L31, so unless it's not used it's not fixed :)

**Comment by noahdietz** [comment]
Really, I think the request body should be prepared as an object and just dropped in to the template. Example in [another project](https://github.com/noahdietz/oatts/blob/master/templates/transactionLevel.handlebars#L3-L4) (excuse the awkward formatting, whitespace in handlebars is annoying).
